--------------------------------------------------------
--  DDL for Table PERMISSION
--------------------------------------------------------

  CREATE TABLE "PERMISSION" 
   (	"PERMISSION_ID" NUMBER(10,0), 
	"NAME" VARCHAR2(255 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PERMISSION
SET DEFINE OFF;
Insert into PERMISSION (PERMISSION_ID,NAME) values (1,'Users');
Insert into PERMISSION (PERMISSION_ID,NAME) values (2,'Roles');
Insert into PERMISSION (PERMISSION_ID,NAME) values (3,'Permissions');
Insert into PERMISSION (PERMISSION_ID,NAME) values (4,'Reports');
Insert into PERMISSION (PERMISSION_ID,NAME) values (5,'Student Assignment');
Insert into PERMISSION (PERMISSION_ID,NAME) values (6,'Teacher Assignment');
--------------------------------------------------------
--  DDL for Index SYS_C005167
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C005167" ON "PERMISSION" ("PERMISSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_6X5RL8V0AKU5524GWLR5DWX8E
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_6X5RL8V0AKU5524GWLR5DWX8E" ON "PERMISSION" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PERMISSION
--------------------------------------------------------

  ALTER TABLE "PERMISSION" MODIFY ("PERMISSION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PERMISSION" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "PERMISSION" ADD PRIMARY KEY ("PERMISSION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "PERMISSION" ADD CONSTRAINT "UK_6X5RL8V0AKU5524GWLR5DWX8E" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
