--------------------------------------------------------
--  DDL for Table PORTAL_USER
--------------------------------------------------------


  CREATE TABLE "PORTAL_USER" 
   (	"USER_ID" NUMBER(10,0), 
	"ADDRESS" VARCHAR2(255 CHAR), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"ENABLED" VARCHAR2(255 CHAR), 
	"FNAME" VARCHAR2(255 CHAR), 
	"LNAME" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"PHONE" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR), 
	"GENDER" VARCHAR2(255 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;

Insert into PORTAL_USER (USER_ID,ADDRESS,EMAIL,ENABLED,FNAME,LNAME,PASSWORD,PHONE,USERNAME,GENDER) values (1,'Nill','admin@fonixdevelopers.com','TRUE','Admin','Portal','123456','111128128','admin','M');
--------------------------------------------------------
--  DDL for Index SYS_C005161
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C005161" ON "PORTAL_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_2B3HB3DYQQ6R7QM8W8AM89PMO
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_2B3HB3DYQQ6R7QM8W8AM89PMO" ON "PORTAL_USER" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PORTAL_USER
--------------------------------------------------------

  ALTER TABLE "PORTAL_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PORTAL_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "PORTAL_USER" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "PORTAL_USER" ADD CONSTRAINT "UK_2B3HB3DYQQ6R7QM8W8AM89PMO" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
