--------------------------------------------------------
--  DDL for Table ROLE_PERMISSION
--------------------------------------------------------

  CREATE TABLE "ROLE_PERMISSION" 
   (	"ROLE_ROLE_ID" NUMBER(10,0), 
	"PERMISSIONS_PERMISSION_ID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ROLE_PERMISSION
SET DEFINE OFF;
Insert into ROLE_PERMISSION (ROLE_ROLE_ID,PERMISSIONS_PERMISSION_ID) values (1,1);
Insert into ROLE_PERMISSION (ROLE_ROLE_ID,PERMISSIONS_PERMISSION_ID) values (1,2);
Insert into ROLE_PERMISSION (ROLE_ROLE_ID,PERMISSIONS_PERMISSION_ID) values (1,3);
--------------------------------------------------------
--  DDL for Index SYS_C005175
--------------------------------------------------------

--  CREATE UNIQUE INDEX "SYS_C005175" ON "ROLE_PERMISSION" ("ROLE_ROLE_ID", "PERMISSIONS_PERMISSION_ID") 
--  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
--  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
--  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ROLE_PERMISSION
--------------------------------------------------------

  ALTER TABLE "ROLE_PERMISSION" MODIFY ("ROLE_ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ROLE_PERMISSION" MODIFY ("PERMISSIONS_PERMISSION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ROLE_PERMISSION" ADD PRIMARY KEY ("ROLE_ROLE_ID", "PERMISSIONS_PERMISSION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROLE_PERMISSION
--------------------------------------------------------

  ALTER TABLE "ROLE_PERMISSION" ADD CONSTRAINT "FK_15G0YON0OH0AFYGAOMKTUO69D" FOREIGN KEY ("PERMISSIONS_PERMISSION_ID")
	  REFERENCES "PERMISSION" ("PERMISSION_ID") ENABLE;
 
  ALTER TABLE "ROLE_PERMISSION" ADD CONSTRAINT "FK_OE2X4TVWN5TJ7MJ8YNYYH61CO" FOREIGN KEY ("ROLE_ROLE_ID")
	  REFERENCES "ROLE" ("ROLE_ID") ENABLE;
